'use client';
import {useEffect,useState} from 'react';
import {Input} from '@/components/ui/input';import {Button} from '@/components/ui/button';
import {Eye,EyeOff} from 'lucide-react';import {authConfigured,browserSupabase} from '@/lib/supabase/browser';
export function AuthForm({recovery=false,initialMode='login'}:{recovery?:boolean;initialMode?:'login'|'signup'}){
 const [mode,setMode]=useState<'login'|'signup'|'forgot'>(initialMode),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[sessionReady,setSessionReady]=useState(!recovery);
 useEffect(()=>{if(!authConfigured())return;const client=browserSupabase();if(new URLSearchParams(window.location.search).has('auth_error'))setError('O link expirou ou não pôde ser validado. Solicite outro.');if(recovery){client.auth.getSession().then(({data,error})=>{if(error||!data.session)setError('Abra o link de recuperação recebido por e-mail.');else setSessionReady(true);});const {data}=client.auth.onAuthStateChange((_event,session)=>{if(session)setSessionReady(true);});return()=>data.subscription.unsubscribe();}},[recovery]);
 const change=(next:typeof mode)=>{setMode(next);setError('');setMessage('');};
 return <><h2>{recovery?'Defina sua nova senha':mode==='signup'?'Crie sua conta':mode==='forgot'?'Recupere seu acesso':'Bom ter você aqui.'}</h2><p className="login-subtitle">{recovery?'Escolha uma senha de pelo menos 12 caracteres.':mode==='signup'?'Comece a organizar sua empresa.':mode==='forgot'?'Enviaremos um link para redefinir sua senha.':'Entre para acompanhar seu negócio.'}</p>
 {!authConfigured()&&<p className="login-setup" role="status">A conexão com o Supabase ainda precisa ser configurada para liberar o acesso.</p>}
 <form className="login-fields" key={mode} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');const f=new FormData(e.currentTarget),email=String(f.get('email')||'').trim(),password=String(f.get('password')||'');try{const client=browserSupabase();if(recovery){if(password!==f.get('confirm'))throw new Error('As senhas não coincidem.');const r=await client.auth.updateUser({password});if(r.error)throw new Error('Não foi possível alterar a senha. Solicite um novo link e tente novamente.');await client.auth.signOut();window.location.replace('/login');}
 else if(mode==='login'){const {error}=await client.auth.signInWithPassword({email,password});if(error)throw new Error('Confira e-mail e senha e confirme seu e-mail antes de entrar.');window.location.replace('/');}
 else if(mode==='signup'){if(password!==f.get('confirm'))throw new Error('As senhas não coincidem.');const r=await client.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+'/auth/confirm'}});if(r.error)throw new Error('Não foi possível criar a conta. Confira os dados ou tente novamente mais tarde.');if(r.data.session)window.location.replace('/');else setMessage('Conta criada. Confira seu e-mail e clique no link de confirmação antes de entrar.');}
 else{const r=await client.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/auth/confirm?recovery=1'});if(r.error)throw new Error('Não foi possível enviar agora. Tente novamente mais tarde.');setMessage('Se houver uma conta com esse e-mail, você receberá as instruções de recuperação.');}
 }catch(e){setError(e instanceof Error?e.message:'Não foi possível continuar.');}finally{setBusy(false);}}}>
 <fieldset disabled={busy||!authConfigured()||!sessionReady} className="auth-fieldset">
 {!recovery&&<label htmlFor="auth-email">E-mail<Input id="auth-email" name="email" type="email" required maxLength={254} autoComplete="username" placeholder="voce@empresa.com.br"/></label>}
 {(recovery||mode!=='forgot')&&<label htmlFor="auth-password">Senha<span className="login-password"><Input id="auth-password" name="password" type={visible?'text':'password'} required minLength={mode==='signup'||recovery?12:1} maxLength={128} autoComplete={mode==='signup'||recovery?'new-password':'current-password'}/><Button type="button" variant="ghost" size="icon" onClick={()=>setVisible(v=>!v)} aria-label={visible?'Ocultar senha':'Mostrar senha'}>{visible?<EyeOff/>:<Eye/>}</Button></span></label>}
 {(recovery||mode==='signup')&&<label htmlFor="auth-confirm">Confirme a senha<Input id="auth-confirm" name="confirm" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label>}
 <Button type="submit" className="login-submit">{busy?'Aguarde…':recovery?'Salvar nova senha':mode==='signup'?'Criar conta':mode==='forgot'?'Enviar link':'Entrar'}</Button></fieldset></form>
 {error&&<p role="alert" className="notice error-notice">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}
 {!recovery&&<div className="auth-links">{mode==='login'?<><Button type="button" variant="link" onClick={()=>change('forgot')}>Esqueci minha senha</Button><a className="auth-create-link" href="/cadastro">Criar conta</a></>:mode==='forgot'?<Button type="button" variant="link" onClick={()=>change('login')}>Voltar para entrar</Button>:<a className="auth-create-link" href="/login">Já tenho conta</a>}</div>}
 </>;
}
