import {useState} from 'react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {NativeSelect} from '@/components/ui/native-select';
import {type Client,type VisitLocation,formatAddress} from '@/lib/customer-rules';
import {type Company} from '@/lib/workspace-model';
import {businessDay} from '@/lib/company-settings';
export function BookingForm({company,clients,date,disabled,onSave}:{company:Company;clients:Client[];date:string;disabled:boolean;onSave:(payload:unknown)=>Promise<unknown>}){
 const [client,setClient]=useState(''),[location,setLocation]=useState<VisitLocation>('customer'),[serviceId,setServiceId]=useState(company.settings.services.find(s=>s.active)?.id??'');
 const services=company.settings.services.filter(s=>s.active),selected=services.find(s=>s.id===serviceId),day=businessDay(date,company.settings);
 return <form className="entry-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSave({client,date,time:String(f.get('time')),duration:selected?.duration??Number(f.get('duration')),serviceId,location,companyVersion:company.version});}}><fieldset className="form-fieldset" disabled={disabled}><label>Cliente<NativeSelect required value={client} onChange={e=>setClient(e.target.value)}><option value="" disabled>Selecione</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</NativeSelect></label><label>Horário<Input name="time" type="time" required min={day?.open} max={day?.close} defaultValue={day?.open}/></label>{company.settings.services.length>0?<label>Serviço<NativeSelect required value={serviceId} onChange={e=>setServiceId(e.target.value)}><option value="" disabled>Selecione um serviço ativo</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} · {s.duration} min</option>)}</NativeSelect></label>:<label>Duração em minutos<Input name="duration" type="number" min={5} max={480} required defaultValue={30}/></label>}{company.mode==='both'&&<label>Local<NativeSelect value={location} onChange={e=>setLocation(e.target.value as VisitLocation)}><option value="customer">No endereço do cliente</option><option value="business">No estabelecimento</option></NativeSelect></label>}<p className="booking-location">{company.mode==='customer'||(company.mode==='both'&&location==='customer')?'Endereço: '+formatAddress(clients.find(c=>c.id===client)?.address):'Atendimento no estabelecimento.'}</p>{!day?.enabled&&<p className="notice">A empresa está fechada nesta data.</p>}{company.settings.services.length>0&&!services.length&&<p className="notice">Ative um serviço em Empresa e Configurações para agendar.</p>}<Button type="submit" disabled={!day?.enabled||(company.settings.services.length>0&&!services.length)}>{disabled?'Salvando…':'Agendar'}</Button></fieldset></form>;
}
