'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {AddressFields} from './customer-form';
import {readAddress,hasAddress,type AttendanceMode} from '@/lib/customer-rules';
import {sectors,timezones,weekdays,type CompanySettings as Settings} from '@/lib/company-settings';
import type {Company} from '@/lib/workspace-model';
export function CompanySettings({company,disabled,onSave,onLogo,logoUrl}:{logoUrl?:string;company:Company;disabled:boolean;onSave:(payload:unknown)=>Promise<unknown>;onLogo:(data:FormData)=>Promise<void>}){
 const [settings,setSettings]=useState<Settings>(company.settings);
 const [dirty,setDirty]=useState(false);
 const [mode,setMode]=useState<AttendanceMode>(company.mode);
 const patchDay=(index:number,patch:Partial<Settings['hours'][number]>)=>setSettings(s=>({...s,hours:s.hours.map((h,i)=>i===index?{...h,...patch}:h)}));
 return <section className="panel company-settings settings-full"><div className="section-title"><div><h2>Empresa e Configurações</h2><p className="muted">Defina como sua empresa aparece e organiza os atendimentos.</p></div></div>
 <form className="logo-form" onSubmit={async e=>{e.preventDefault();const f=e.currentTarget;const data=new FormData(f);data.set('version',String(company.version));await onLogo(data);}}><div>{company.hasLogo?<img className="company-logo" src={logoUrl??('/api/company-logo?v='+company.version)} alt={'Logo de '+company.name}/>:<span className="company-logo logo-placeholder">{company.name.slice(0,1)}</span>}</div><label>Logo da empresa<Input type="file" name="file" accept="image/png,image/jpeg,image/webp" required disabled={disabled||dirty}/><small>PNG, JPEG ou WebP, até 2 MB. Salve alterações do formulário antes de trocar o logo.</small></label><Button type="submit" variant="outline" disabled={disabled||dirty}>Salvar logo</Button></form>
 <form onChange={()=>setDirty(true)} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),a=readAddress(f);await onSave({name:String(f.get('name')),mode,version:company.version,settings:{...settings,sector:String(f.get('sector')),phone:String(f.get('phone')),email:String(f.get('email')),address:hasAddress(a)?a:undefined}});}}>
 <fieldset disabled={disabled} className="settings-fieldset"><div className="settings-section"><h3>Informações da empresa</h3><div className="settings-grid"><label>Nome da empresa<Input name="name" required maxLength={100} defaultValue={company.name}/></label><label>Ramo de atividade<NativeSelect name="sector" required defaultValue={settings.sector}><option value="" disabled>Selecione</option>{sectors.map(s=><option key={s}>{s}</option>)}</NativeSelect></label><label>Telefone de contato (opcional)<Input type="tel" name="phone" maxLength={20} defaultValue={settings.phone} placeholder="(11) 99999-9999"/></label><label>E-mail de contato (opcional)<Input type="email" name="email" maxLength={254} defaultValue={settings.email}/></label></div><p className="muted">Este e-mail é um contato da empresa; não altera o login da sua conta.</p><AddressFields title="Endereço da empresa" initial={settings.address}/></div>
 <div className="settings-section"><h3>Forma de atendimento</h3><label>Onde sua empresa atende?<NativeSelect value={mode} onChange={e=>setMode(e.target.value as AttendanceMode)}><option value="business">No estabelecimento</option><option value="customer">No endereço do cliente</option><option value="both">Nos dois locais</option></NativeSelect></label><p className="muted">A escolha vale para qualquer ramo. {mode==='customer'?'O endereço é obrigatório no cadastro do cliente, e a agenda oferece rotas.':mode==='business'?'Novos clientes precisam de nome e telefone. A agenda não oferece rotas.':'O endereço é opcional no cadastro e obrigatório nas visitas externas.'}</p></div>
 <div className="settings-section"><h3>Horários de funcionamento</h3><label>Fuso horário<NativeSelect value={settings.timezone} onChange={e=>setSettings(s=>({...s,timezone:e.target.value}))}>{timezones.map(t=><option key={t} value={t}>{t.replace('America/','').replaceAll('_',' ')}</option>)}</NativeSelect></label><p className="muted">Configure um expediente e um intervalo opcional por dia. Novos atendimentos devem caber nesses horários. Os agendamentos existentes mantêm suas datas e horas; revise-os se mudar o fuso.</p>
 {settings.hours.map((h,i)=><div className="hours-row" key={h.day}><label className="check-label"><input type="checkbox" checked={h.enabled} onChange={e=>patchDay(i,{enabled:e.target.checked})}/>{weekdays[h.day]}</label>{h.enabled?<><label>Abertura<Input aria-label={'Abertura '+weekdays[h.day]} type="time" required value={h.open} onChange={e=>patchDay(i,{open:e.target.value})}/></label><label>Fechamento<Input aria-label={'Fechamento '+weekdays[h.day]} type="time" required value={h.close} onChange={e=>patchDay(i,{close:e.target.value})}/></label><label>Início do intervalo<Input aria-label={'Início do intervalo '+weekdays[h.day]} type="time" value={h.breakStart} onChange={e=>patchDay(i,{breakStart:e.target.value})}/></label><label>Fim do intervalo<Input aria-label={'Fim do intervalo '+weekdays[h.day]} type="time" value={h.breakEnd} onChange={e=>patchDay(i,{breakEnd:e.target.value})}/></label></>:<span className="muted">Fechado</span>}</div>)}</div>
 <div className="settings-save"><p className="muted">Todas as alterações abaixo do logo são salvas juntas.</p><Button type="submit" disabled={disabled}>{disabled?'Salvando…':'Salvar configurações'}</Button></div></fieldset></form></section>;
}
