'use client';
import {useRef,useState} from 'react';
import {Building2,ChevronLeft,ChevronRight,Check,PanelsTopLeft,MapPin} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {AddressFields} from './customer-form';
import {hasAddress,readAddress,type AttendanceMode} from '@/lib/customer-rules';
import {sectors,templateFor,servicesFor,moduleNames,type CompanySettings} from '@/lib/company-settings';
import type {Company} from '@/lib/workspace-model';
export function CompanyOnboarding({company,disabled,onSave}:{company:Company;disabled:boolean;onSave:(payload:unknown)=>Promise<unknown>}){
 const [step,setStep]=useState(1),[sector,setSector]=useState(''),[mode,setMode]=useState<AttendanceMode>('business'),[error,setError]=useState('');
 const formRef=useRef<HTMLFormElement>(null);
 function choose(value:string){setSector(value);setMode(templateFor(value).mode);setError('');}
 function next(){if(step===1&&sector.trim().length<2){setError('Escreva o ramo de atividade da sua empresa.');return;}setError('');setStep(value=>Math.min(3,value+1));}
 const template=templateFor(sector),suggestedServices=servicesFor(sector);
 return <div className="onboarding-shell"><header className="onboarding-brand"><span>órbita.</span><small>Configuração da empresa</small></header><main className="onboarding-card"><div className="onboarding-progress"><span>Etapa {step} de 3</span><div>{[1,2,3].map(number=><i key={number} className={number<=step?'active':''}/>)}</div></div>
  {step===1&&<section className="sector-entry"><p className="eyebrow">CONHEÇA SEU NEGÓCIO</p><h1>Qual é o ramo da sua empresa?</h1><p className="onboarding-intro">Escreva como você descreve seu negócio. O Órbita será configurado a partir dessa informação e você poderá alterar tudo depois.</p><label className="sector-input-label">Ramo de atividade<Input value={sector} onChange={event=>setSector(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')next();}} maxLength={80} autoFocus placeholder="Ex.: Pet shop, contabilidade, loja de roupas…"/></label><div className="sector-suggestions"><span>Alguns exemplos:</span>{sectors.map(value=><button type="button" key={value} className={sector.toLocaleLowerCase('pt-BR')===value.toLocaleLowerCase('pt-BR')?'selected':''} onClick={()=>choose(value)}>{value}</button>)}</div><div className="sector-free-note"><Check/><div><strong>Qualquer tipo de empresa pode usar</strong><small>Se o ramo não estiver nos exemplos, basta escrever. Você cadastrará os próprios serviços e valores depois.</small></div></div></section>}
  {step===2&&sector&&<section><p className="eyebrow">COMO VOCÊ ATENDE</p><h1>Onde os atendimentos acontecem?</h1><p className="onboarding-intro">Isso define quando endereço e rota serão solicitados.</p><div className="attendance-grid">{([{id:'business',title:'No estabelecimento',text:'O cliente vai até a empresa.',icon:Building2},{id:'customer',title:'No endereço do cliente',text:'Sua equipe se desloca para atender.',icon:MapPin},{id:'both',title:'Das duas formas',text:'Atende na empresa e também fora.',icon:PanelsTopLeft}] as const).map(item=><button type="button" key={item.id} onClick={()=>setMode(item.id)} className={'attendance-card '+(mode===item.id?'selected':'')}><item.icon/><strong>{item.title}</strong><small>{item.text}</small></button>)}</div><div className="module-preview"><h2>Estrutura inicial para {sector}</h2><div>{template.modules.map(id=><span key={id}><Check/> {moduleNames[id]}</span>)}</div></div></section>}
  {step===3&&sector&&<section><p className="eyebrow">DADOS DA EMPRESA</p><h1>Complete o cadastro</h1><p className="onboarding-intro">Essas informações identificam sua empresa nos atendimentos e documentos.</p><form ref={formRef} id="onboarding-form" className="onboarding-form" onInvalid={()=>setError('Preencha os campos obrigatórios destacados para continuar.')} onSubmit={async event=>{event.preventDefault();setError('');const form=new FormData(event.currentTarget),address=readAddress(form);const settings:CompanySettings={...company.settings,sector:sector.trim(),phone:String(form.get('phone')||''),email:String(form.get('email')||''),address:hasAddress(address)?address:undefined,services:suggestedServices,modules:template.modules,onboardingComplete:true};const saved=await onSave({name:String(form.get('name')||''),mode,version:company.version,settings});if(!saved)setError('Não foi possível concluir. Confira telefone, endereço e os campos obrigatórios.');}}><div className="settings-grid"><label>Nome da empresa<Input name="name" required maxLength={100} autoFocus placeholder="Nome que seus clientes conhecem"/></label><label>Telefone com DDD<Input name="phone" type="tel" required maxLength={20} placeholder="(11) 99999-9999"/></label><label>E-mail da empresa <small>Opcional</small><Input name="email" type="email" maxLength={254} placeholder="contato@empresa.com"/></label><label>Ramo de atividade<Input value={sector} disabled/></label></div><AddressFields title="Endereço da empresa" required={mode!=='customer'}/></form><div className="onboarding-summary"><strong>Próximo passo: cadastrar serviços e valores</strong>{suggestedServices.length?<><p>Preparamos algumas sugestões: {suggestedServices.map(service=>service.name).join(', ')}.</p><small>Você poderá editar os nomes, definir valores, criar planos mensais ou remover as sugestões.</small></>:<><p>Como este ramo foi informado por você, o catálogo começará vazio.</p><small>Na aba Serviços, cadastre exatamente o que sua empresa oferece, com duração e forma de cobrança.</small></>}</div></section>}
  {error&&<p role="alert" className="notice error-notice">{error}</p>}<footer className="onboarding-actions">{step>1?<Button variant="outline" onClick={()=>setStep(value=>value-1)} disabled={disabled}><ChevronLeft/>Voltar</Button>:<span/>}{step<3?<Button onClick={next}>Continuar<ChevronRight/></Button>:<Button type="button" onClick={()=>{if(!formRef.current)return;setError('');formRef.current.requestSubmit();}} disabled={disabled}>{disabled?'Criando empresa…':'Concluir e acessar o sistema'}<Check/></Button>}</footer>
 </main></div>
}
