'use client';
import {useState} from 'react';
import {Building2,ChevronLeft,ChevronRight,Check,Scissors,Stethoscope,Dumbbell,Wrench,PanelsTopLeft,MapPin} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {AddressFields} from './customer-form';
import {hasAddress,readAddress,type AttendanceMode} from '@/lib/customer-rules';
import {sectors,sectorTemplates,servicesFor,moduleNames,type Sector,type CompanySettings} from '@/lib/company-settings';
import type {Company} from '@/lib/workspace-model';
const icons={Vidraçaria:PanelsTopLeft,Mecânica:Wrench,'Personal trainer':Dumbbell,Clínica:Stethoscope,Barbearia:Scissors,'Salão de beleza':Scissors};
export function CompanyOnboarding({company,disabled,onSave}:{company:Company;disabled:boolean;onSave:(payload:unknown)=>Promise<unknown>}){
 const [step,setStep]=useState(1),[sector,setSector]=useState<Sector|null>(null),[mode,setMode]=useState<AttendanceMode>('business'),[error,setError]=useState('');
 function choose(value:Sector){const template=sectorTemplates[value];setSector(value);setMode(template.mode);setError('');}
 function next(){if(step===1&&!sector){setError('Escolha o tipo da sua empresa.');return;}setError('');setStep(s=>Math.min(3,s+1));}
 return <div className="onboarding-shell"><header className="onboarding-brand"><span>órbita.</span><small>Configuração da empresa</small></header><main className="onboarding-card"><div className="onboarding-progress"><span>Etapa {step} de 3</span><div>{[1,2,3].map(n=><i key={n} className={n<=step?'active':''}/>)}</div></div>
  {step===1&&<section><p className="eyebrow">CONHEÇA SEU NEGÓCIO</p><h1>Qual é o tipo da sua empresa?</h1><p className="onboarding-intro">Vamos preparar o sistema com as ferramentas, serviços e linguagem mais adequados. Você poderá alterar tudo depois.</p><div className="sector-grid">{sectors.map(value=>{const Icon=icons[value];return <button type="button" className={'sector-card '+(sector===value?'selected':'')} key={value} onClick={()=>choose(value)}><span><Icon/></span><strong>{value}</strong><small>{sectorTemplates[value].description}</small>{sector===value&&<Check className="sector-check"/>}</button>})}</div></section>}
  {step===2&&sector&&<section><p className="eyebrow">COMO VOCÊ ATENDE</p><h1>Onde os atendimentos acontecem?</h1><p className="onboarding-intro">Isso define quando endereço e rota serão solicitados.</p><div className="attendance-grid">{([{id:'business',title:'No estabelecimento',text:'O cliente vai até a empresa.',icon:Building2},{id:'customer',title:'No endereço do cliente',text:'Sua equipe se desloca para atender.',icon:MapPin},{id:'both',title:'Das duas formas',text:'Atende na empresa e também fora.',icon:PanelsTopLeft}] as const).map(item=><button type="button" key={item.id} onClick={()=>setMode(item.id)} className={'attendance-card '+(mode===item.id?'selected':'')}><item.icon/><strong>{item.title}</strong><small>{item.text}</small></button>)}</div><div className="module-preview"><h2>Ferramentas recomendadas para {sector}</h2><div>{sectorTemplates[sector].modules.map(id=><span key={id}><Check/> {moduleNames[id]}</span>)}</div></div></section>}
  {step===3&&sector&&<section><p className="eyebrow">DADOS DA EMPRESA</p><h1>Complete o cadastro</h1><p className="onboarding-intro">Essas informações identificam sua empresa nos atendimentos e documentos.</p><form id="onboarding-form" className="onboarding-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),address=readAddress(f),template=sectorTemplates[sector];const settings:CompanySettings={...company.settings,sector,phone:String(f.get('phone')||''),email:String(f.get('email')||''),address:hasAddress(address)?address:undefined,services:servicesFor(sector),modules:template.modules,onboardingComplete:true};await onSave({name:String(f.get('name')||''),mode,version:company.version,settings});}}><div className="settings-grid"><label>Nome da empresa<Input name="name" required maxLength={100} autoFocus placeholder="Nome que seus clientes conhecem"/></label><label>Telefone com DDD<Input name="phone" type="tel" required maxLength={20} placeholder="(11) 99999-9999"/></label><label>E-mail da empresa <small>Opcional</small><Input name="email" type="email" maxLength={254} placeholder="contato@empresa.com"/></label><label>Tipo de empresa<Input value={sector} disabled/></label></div><AddressFields title="Endereço da empresa" required={mode!=='customer'}/></form><div className="onboarding-summary"><strong>O Órbita vai começar com:</strong><p>{servicesFor(sector).map(s=>s.name).join(', ')}.</p><small>São sugestões iniciais. Você poderá adicionar, editar ou desativar serviços.</small></div></section>}
  {error&&<p role="alert" className="notice error-notice">{error}</p>}<footer className="onboarding-actions">{step>1?<Button variant="outline" onClick={()=>setStep(s=>s-1)} disabled={disabled}><ChevronLeft/>Voltar</Button>:<span/>}{step<3?<Button onClick={next}>Continuar<ChevronRight/></Button>:<Button form="onboarding-form" type="submit" disabled={disabled}>{disabled?'Criando empresa…':'Concluir e acessar o sistema'}<Check/></Button>}</footer>
 </main></div>
}
