'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {AddressFields} from './customer-form';
import {readAddress,hasAddress} from '@/lib/customer-rules';
import {timezones,weekdays,type CompanySettings as Settings} from '@/lib/company-settings';
import type {Company} from '@/lib/workspace-model';

export function CompanySettings({company,disabled,onSave,onLogo,onDeleteAccount,logoUrl}:{logoUrl?:string;company:Company;disabled:boolean;onSave:(payload:unknown)=>Promise<unknown>;onLogo:(data:FormData)=>Promise<void>;onDeleteAccount:(confirmation:string)=>Promise<void>}){
 const [settings,setSettings]=useState<Settings>(company.settings),[dirty,setDirty]=useState(false),[deleteOpen,setDeleteOpen]=useState(false),[confirmation,setConfirmation]=useState('');
 const patchDay=(index:number,patch:Partial<Settings['hours'][number]>)=>setSettings(current=>({...current,hours:current.hours.map((hours,i)=>i===index?{...hours,...patch}:hours)}));
 return <section className="panel company-settings settings-full"><div className="section-title"><div><h2>Minha barbearia</h2><p className="muted">Atualize os dados, a logo e os horários de funcionamento.</p></div></div>
 <form className="logo-form" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form);data.set('version',String(company.version));await onLogo(data);}}><div>{company.hasLogo?<img className="company-logo" src={logoUrl??('/api/company-logo?v='+company.version)} alt={'Logo de '+company.name}/>:<span className="company-logo logo-placeholder">{company.name.slice(0,1)}</span>}</div><label>Logo da barbearia<Input type="file" name="file" accept="image/png,image/jpeg,image/webp" required disabled={disabled||dirty}/><small>PNG, JPEG ou WebP, até 2 MB.</small></label><Button type="submit" variant="outline" disabled={disabled||dirty}>Salvar logo</Button></form>
 <form onChange={()=>setDirty(true)} onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget),address=readAddress(form);await onSave({name:String(form.get('name')),mode:'business',version:company.version,settings:{...settings,sector:'Barbearia',modules:['agenda','customers','professionals','resources'],phone:String(form.get('phone')),email:String(form.get('email')),address:hasAddress(address)?address:undefined}});}}>
 <fieldset disabled={disabled} className="settings-fieldset"><div className="settings-section"><h3>Dados da barbearia</h3><div className="settings-grid"><label>Nome da barbearia<Input name="name" required maxLength={100} defaultValue={company.name}/></label><label>Telefone<Input type="tel" name="phone" required maxLength={20} defaultValue={settings.phone} placeholder="(11) 99999-9999"/></label><label>E-mail <small>Opcional</small><Input type="email" name="email" maxLength={254} defaultValue={settings.email}/></label></div><AddressFields title="Endereço da barbearia" required initial={settings.address}/></div>
 <div className="settings-section"><h3>Horários de funcionamento</h3><label>Fuso horário<NativeSelect value={settings.timezone} onChange={event=>setSettings(current=>({...current,timezone:event.target.value}))}>{timezones.map(timezone=><option key={timezone} value={timezone}>{timezone.replace('America/','').replaceAll('_',' ')}</option>)}</NativeSelect></label><p className="muted">Configure o expediente e um intervalo opcional por dia.</p>
 {settings.hours.map((hours,index)=><div className="hours-row" key={hours.day}><label className="check-label"><input type="checkbox" checked={hours.enabled} onChange={event=>patchDay(index,{enabled:event.target.checked})}/>{weekdays[hours.day]}</label>{hours.enabled?<><label>Abertura<Input aria-label={'Abertura '+weekdays[hours.day]} type="time" required value={hours.open} onChange={event=>patchDay(index,{open:event.target.value})}/></label><label>Fechamento<Input aria-label={'Fechamento '+weekdays[hours.day]} type="time" required value={hours.close} onChange={event=>patchDay(index,{close:event.target.value})}/></label><label>Início do intervalo<Input aria-label={'Início do intervalo '+weekdays[hours.day]} type="time" value={hours.breakStart} onChange={event=>patchDay(index,{breakStart:event.target.value})}/></label><label>Fim do intervalo<Input aria-label={'Fim do intervalo '+weekdays[hours.day]} type="time" value={hours.breakEnd} onChange={event=>patchDay(index,{breakEnd:event.target.value})}/></label></>:<span className="muted">Fechado</span>}</div>)}</div>
 <div className="settings-save"><p className="muted">As alterações deste formulário são salvas juntas.</p><Button type="submit" disabled={disabled}>{disabled?'Salvando…':'Salvar alterações'}</Button></div></fieldset></form>
 <section className="danger-zone"><div><h3>Excluir conta e barbearia</h3><p>Apaga clientes, agendamentos, planos, arquivos e o acesso da conta. Esta ação é definitiva.</p></div>{!deleteOpen?<Button type="button" variant="outline" onClick={()=>setDeleteOpen(true)}>Excluir minha conta</Button>:<div className="delete-confirm"><label>Digite <strong>EXCLUIR MINHA CONTA</strong><Input value={confirmation} onChange={event=>setConfirmation(event.target.value)} autoComplete="off"/></label><div><Button type="button" variant="outline" onClick={()=>{setDeleteOpen(false);setConfirmation('');}}>Cancelar</Button><Button type="button" disabled={disabled||confirmation!=='EXCLUIR MINHA CONTA'} onClick={()=>onDeleteAccount(confirmation)}>Excluir definitivamente</Button></div></div>}</section></section>;
}

