import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {type Client,type Address,type AttendanceMode,hasAddress} from '@/lib/customer-rules';
export function AddressFields({initial,required=false,title='Endereço'}:{initial?:Address;required?:boolean;title?:string}){return <fieldset className="address-fields"><legend>{title} {required?'obrigatório':'opcional'}</legend><div className="address-grid">
<label className="address-street">Rua / avenida<Input name="street" required={required} maxLength={150} defaultValue={initial?.street} placeholder="Rua / avenida"/></label><label>Número<Input name="number" required={required} maxLength={20} defaultValue={initial?.number} placeholder="123 ou s/n"/></label><label>Bairro<Input name="neighborhood" required={required} maxLength={100} defaultValue={initial?.neighborhood}/></label><label>Cidade<Input name="city" required={required} maxLength={100} defaultValue={initial?.city}/></label><label>UF<Input name="state" required={required} minLength={2} maxLength={2} defaultValue={initial?.state} placeholder="SP"/></label><label>CEP (opcional)<Input name="postalCode" maxLength={9} defaultValue={initial?.postalCode}/></label><label className="address-street">Complemento (opcional)<Input name="complement" maxLength={150} defaultValue={initial?.complement}/></label></div></fieldset>}
export function CustomerForm({mode,initial,onSave,onCancel,disabled=false}:{mode:AttendanceMode;initial?:Client;onSave:(data:FormData)=>Promise<boolean>;onCancel?:()=>void;disabled?:boolean}){
 const [pending,setPending]=useState(false);
 return <form className="entry-form customer-form" onSubmit={async e=>{e.preventDefault();if(pending||disabled)return;const form=e.currentTarget;const data=new FormData(form);setPending(true);try{if(await onSave(data))form.reset();}finally{setPending(false);}}}><fieldset disabled={pending||disabled} className="form-fieldset"><label>Nome<Input name="name" required maxLength={100} defaultValue={initial?.name}/></label><label>Telefone<Input name="phone" type="tel" required minLength={10} maxLength={20} defaultValue={initial?.phone} placeholder="(11) 99999-9999"/></label>{(mode!=='business'||hasAddress(initial?.address))&&<AddressFields initial={initial?.address} required={mode==='customer'}/>}<div className="form-actions"><Button type="submit">{pending?'Salvando…':initial?'Salvar cliente':'Cadastrar cliente'}</Button>{onCancel&&<Button type="button" variant="outline" onClick={onCancel}>Cancelar edição</Button>}</div></fieldset></form>;
}