'use client';
import {useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,Plus,RefreshCw,Scissors,TicketCheck,UsersRound} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import type {Client} from '@/lib/customer-rules';
import type {ClientPlan,Company} from '@/lib/workspace-model';

const formatDate=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('pt-BR');
const addMonth=(date:string)=>{const value=new Date(date+'T12:00:00Z');value.setUTCMonth(value.getUTCMonth()+1);return value.toISOString().slice(0,10);};
export function MonthlyPlans({company,clients,plans,disabled,onCreate,onUse,onRenew}:{company:Company;clients:Client[];plans:ClientPlan[];disabled:boolean;onCreate:(payload:unknown)=>Promise<unknown>;onUse:(plan:ClientPlan)=>Promise<unknown>;onRenew:(plan:ClientPlan,date:string)=>Promise<unknown>}){
 const services=company.settings.services.filter(service=>service.active&&service.pricingModel==='monthly'),[customerId,setCustomerId]=useState(''),[serviceId,setServiceId]=useState(services[0]?.id??''),[included,setIncluded]=useState(4),[renewsOn,setRenewsOn]=useState(()=>addMonth(new Date().toISOString().slice(0,10))),[filter,setFilter]=useState<'Todos'|'Ativos'|'Próximos'|'Vencidos'>('Todos');
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:company.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),soon=(()=>{const value=new Date(today+'T12:00:00Z');value.setUTCDate(value.getUTCDate()+7);return value.toISOString().slice(0,10)})();
 const status=(plan:ClientPlan)=>plan.renewsOn<today?'Vencido':plan.renewsOn<=soon?'Próximo':'Ativo',counts={active:plans.filter(plan=>status(plan)==='Ativo').length,soon:plans.filter(plan=>status(plan)==='Próximo').length,expired:plans.filter(plan=>status(plan)==='Vencido').length};
 const visible=useMemo(()=>plans.filter(plan=>filter==='Todos'||filter==='Ativos'&&status(plan)==='Ativo'||filter==='Próximos'&&status(plan)==='Próximo'||filter==='Vencidos'&&status(plan)==='Vencido'),[plans,filter,today,soon]);
 const client=(id:string)=>clients.find(item=>item.id===id)?.name??'Cliente';
 return <section className="plans-panel"><div className="plan-metrics"><article><CheckCircle2/><div><strong>{counts.active}</strong><small>clientes ativos</small></div></article><article><AlertTriangle/><div><strong>{counts.soon}</strong><small>próximos do vencimento</small></div></article><article><RefreshCw/><div><strong>{counts.expired}</strong><small>planos vencidos</small></div></article><article><TicketCheck/><div><strong>{plans.reduce((sum,plan)=>sum+Math.max(0,plan.includedUses-plan.usedUses),0)}</strong><small>usos disponíveis</small></div></article></div>
 <section className="panel plan-create"><div className="section-title"><div><h2>Novo plano mensal</h2><p className="muted">Vincule um cliente a um serviço configurado como plano mensal.</p></div></div>{services.length===0?<p className="notice">Crie ou altere um serviço para a cobrança “Plano mensal” na aba Serviços e planos.</p>:<div className="plan-form"><label>Cliente<NativeSelect required value={customerId} onChange={event=>setCustomerId(event.target.value)}><option value="">Selecione</option>{clients.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</NativeSelect></label><label>Plano<NativeSelect value={serviceId} onChange={event=>setServiceId(event.target.value)}>{services.map(service=><option value={service.id} key={service.id}>{service.name}</option>)}</NativeSelect></label><label>Cortes incluídos<Input type="number" min={1} max={100} value={included} onChange={event=>setIncluded(Number(event.target.value))}/></label><label>Próxima renovação<Input type="date" value={renewsOn} onChange={event=>setRenewsOn(event.target.value)}/></label><Button disabled={disabled||!customerId||!serviceId} onClick={async()=>{if(await onCreate({customerId,serviceId,includedUses:included,renewsOn}))setCustomerId('');}}><Plus/>Criar plano</Button></div>}</section>
 <section className="panel"><div className="section-title"><div><h2>Clientes com plano</h2><p className="muted">Registre cada corte usado e acompanhe a renovação.</p></div><label className="plan-filter">Situação<NativeSelect value={filter} onChange={event=>setFilter(event.target.value as typeof filter)}><option>Todos</option><option>Ativos</option><option>Próximos</option><option>Vencidos</option></NativeSelect></label></div>
 {visible.length===0?<p className="empty">Nenhum plano nesta situação.</p>:<div className="plan-list">{visible.map(plan=>{const available=Math.max(0,plan.includedUses-plan.usedUses),state=status(plan);return <article className={'plan-card plan-'+state.toLowerCase()} key={plan.id}><header><span><UsersRound/></span><div><strong>{client(plan.customerId)}</strong><small>{plan.serviceName}</small></div><span className="plan-status">{state}</span></header><div className="plan-usage"><div><strong>{available}</strong><small>usos disponíveis</small></div><div><strong>{plan.usedUses}/{plan.includedUses}</strong><small>utilizados no ciclo</small></div><div><strong>{formatDate(plan.renewsOn)}</strong><small>próxima renovação</small></div></div><footer><Button variant="outline" disabled={disabled||available===0||state==='Vencido'} onClick={()=>void onUse(plan)}><Scissors/>Registrar uso</Button><Button disabled={disabled} onClick={()=>void onRenew(plan,addMonth(plan.renewsOn<today?today:plan.renewsOn))}><RefreshCw/>Renovar por um mês</Button></footer></article>})}</div>}</section>
 </section>;
}

