import type {Service} from '@/lib/company-settings';
import {useState} from 'react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';import {NativeSelect} from '@/components/ui/native-select';
import {AddressFields} from './customer-form';import {type Client,type AttendanceMode} from '@/lib/customer-rules';import {type Order,orderStatuses} from '@/lib/workspace-model';
import {businessProfile} from '@/lib/business-profile';
export function OrderForm({services,clients,mode,sector,initial,onSave,onCancel,disabled}:{services:Service[];clients:Client[];mode:AttendanceMode;sector:string;initial?:Order;onSave:(data:FormData)=>Promise<boolean>;onCancel:()=>void;disabled:boolean}){
 const [customerId,setCustomerId]=useState(initial?.customerId??'');const [pending,setPending]=useState(false);const source=initial?.customerId===customerId?initial.address:clients.find(c=>c.id===customerId)?.address;
 const profile=businessProfile(sector);
 return <form className="entry-form customer-form order-form" onSubmit={async e=>{e.preventDefault();if(pending||disabled)return;const data=new FormData(e.currentTarget);setPending(true);try{await onSave(data);}finally{setPending(false);}}}><fieldset className="form-fieldset" disabled={disabled||pending}><label>{profile.customerSingular[0].toUpperCase()+profile.customerSingular.slice(1)}<NativeSelect name="customerId" required value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="" disabled>Selecione</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</NativeSelect></label><label>Serviço<Input name="service" list="company-services" required maxLength={120} defaultValue={initial?.service} placeholder="Selecione ou descreva o serviço"/><datalist id="company-services">{services.filter(s=>s.active).map(s=><option key={s.id} value={s.name}/>)}</datalist></label><label className="full-field">{profile.requestLabel}<Textarea name="description" required maxLength={3000} defaultValue={initial?.description} placeholder="Descreva o que precisa ser feito."/></label><label className="full-field">{profile.extraLabel} (opcional)<Textarea name="measurements" maxLength={1000} defaultValue={initial?.measurements} placeholder={profile.extraPlaceholder}/></label><label>Responsável (opcional)<Input name="responsible" maxLength={100} defaultValue={initial?.responsible} placeholder="Quem acompanha"/></label><label>Etapa<NativeSelect name="status" defaultValue={initial?.status??'Novo'}>{orderStatuses.map(s=><option key={s}>{s}</option>)}</NativeSelect></label><AddressFields key={customerId} initial={source} required={mode==='customer'} title={profile.siteLabel}/><p className="muted full-field">Confira o local do atendimento. Fotos podem ser anexadas depois de salvar.</p><div className="form-actions"><Button type="submit">{pending?'Salvando…':initial?'Salvar alterações':'Criar '+profile.workSingular}</Button><Button type="button" variant="outline" onClick={onCancel}>Cancelar</Button></div></fieldset></form>;
}
