'use client';
import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,Check,Clock,Phone,Scissors,UserRound} from 'lucide-react';

type Service={id:string;name:string;description:string;duration:number;price:number;pricingModel:'fixed'|'monthly'|'quote'};
type Day={day:number;enabled:boolean;open:string;close:string;breakStart:string;breakEnd:string};
type PublicData={company:{id:string;name:string;timezone:string;hours:Day[];services:Service[]};bookings:Array<{date:string;time:string;duration:number;status:string}>};
const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const minutes=(time:string)=>{const [hours,mins]=time.split(':').map(Number);return hours*60+mins;};
const clock=(value:number)=>String(Math.floor(value/60)).padStart(2,'0')+':'+String(value%60).padStart(2,'0');
const dateText=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});

export function PublicBooking({empresa}:{empresa:string}){
 const [data,setData]=useState<PublicData|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState<string[]>([]),[date,setDate]=useState(''),[time,setTime]=useState(''),[sending,setSending]=useState(false),[done,setDone]=useState(false);
 useEffect(()=>{fetch('/api/agendar/'+encodeURIComponent(empresa),{cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'Não foi possível abrir a agenda.');setData(body);}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false));},[empresa]);
 const services=data?.company.services.filter(service=>selected.includes(service.id))??[],duration=services.reduce((sum,service)=>sum+service.duration,0),total=services.reduce((sum,service)=>sum+service.price,0);
 const slots=useMemo(()=>{if(!data||!date||!duration)return[];const day=data.company.hours[new Date(date+'T12:00:00Z').getUTCDay()];if(!day?.enabled)return[];const occupied=data.bookings.filter(booking=>booking.date===date).map(booking=>({start:minutes(booking.time),end:minutes(booking.time)+booking.duration}));const values:string[]=[];for(let start=minutes(day.open);start+duration<=minutes(day.close);start+=15){const end=start+duration;if(day.breakStart&&start<minutes(day.breakEnd)&&end>minutes(day.breakStart))continue;if(occupied.some(item=>start<item.end&&end>item.start))continue;values.push(clock(start));}return values;},[data,date,duration]);
 const today=useMemo(()=>new Date().toLocaleDateString('en-CA',{timeZone:data?.company.timezone||'America/Sao_Paulo'}),[data]),max=useMemo(()=>{const value=new Date();value.setDate(value.getDate()+60);return value.toLocaleDateString('en-CA');},[]);
 if(loading)return <main className="public-booking"><div className="public-card"><p>Carregando agenda…</p></div></main>;
 if(error&&!data)return <main className="public-booking"><div className="public-card"><h1>Agenda indisponível</h1><p>{error}</p></div></main>;
 if(done)return <main className="public-booking"><div className="public-card booking-success"><span><Check/></span><p className="eyebrow">SOLICITAÇÃO ENVIADA</p><h1>Seu horário foi solicitado!</h1><p>A barbearia recebeu seu agendamento para <strong>{dateText(date)}</strong>, às <strong>{time}</strong>.</p><button onClick={()=>{setDone(false);setSelected([]);setDate('');setTime('');}}>Fazer outro agendamento</button></div></main>;
 return <main className="public-booking"><div className="public-card"><header className="public-brand"><span><Scissors/></span><div><small>AGENDAMENTO ONLINE</small><h1>{data!.company.name}</h1></div></header>
  <form onSubmit={async event=>{event.preventDefault();setSending(true);setError('');const form=new FormData(event.currentTarget);try{const response=await fetch('/api/agendar/'+encodeURIComponent(empresa),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.get('name'),phone:form.get('phone'),services:selected,date,time})}),body=await response.json();if(!response.ok)throw new Error(body.error||'Não foi possível agendar.');setDone(true);}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível agendar.');}finally{setSending(false);}}}>
   <section><div className="public-step"><span>1</span><div><h2>Escolha os serviços</h2><p>Você pode selecionar mais de um.</p></div></div><div className="public-services">{data!.company.services.map(service=><label key={service.id} className={selected.includes(service.id)?'selected':''}><input type="checkbox" checked={selected.includes(service.id)} onChange={event=>{setSelected(current=>event.target.checked?[...current,service.id]:current.filter(id=>id!==service.id));setTime('');}}/><div><strong>{service.name}</strong>{service.description&&<small>{service.description}</small>}<span>{service.duration} min {service.price>0?'· '+money(service.price):''}</span></div><i><Check/></i></label>)}</div>{!data!.company.services.length&&<p className="public-empty">A barbearia ainda não cadastrou serviços.</p>}</section>
   <section><div className="public-step"><span>2</span><div><h2>Escolha o horário</h2><p>{duration?duration+' minutos'+(total>0?' · '+money(total):''):'Selecione os serviços primeiro.'}</p></div></div><label className="public-field"><CalendarDays/>Data<input type="date" required min={today} max={max} value={date} disabled={!duration} onChange={event=>{setDate(event.target.value);setTime('');}}/></label>{date&&duration>0&&<><p className="public-date">{dateText(date)}</p><div className="public-slots">{slots.map(slot=><button type="button" key={slot} className={time===slot?'selected':''} onClick={()=>setTime(slot)}><Clock/>{slot}</button>)}</div>{!slots.length&&<p className="public-empty">Não há horários disponíveis neste dia.</p>}</>}</section>
   <section><div className="public-step"><span>3</span><div><h2>Seus dados</h2><p>Para a barbearia confirmar o horário.</p></div></div><label className="public-field"><UserRound/>Nome<input name="name" required maxLength={100} placeholder="Seu nome completo"/></label><label className="public-field"><Phone/>Telefone com DDD<input name="phone" type="tel" required maxLength={20} placeholder="(11) 99999-9999"/></label></section>
   {error&&<p className="public-error">{error}</p>}<button className="public-submit" type="submit" disabled={sending||!selected.length||!date||!time}>{sending?'Enviando…':'Solicitar agendamento'}</button><p className="public-note">O horário fica pendente até a confirmação da barbearia.</p>
  </form>
 </div></main>;
}


