'use client';
import {useState} from 'react';
import {BadgeDollarSign,Clock,Plus,Trash2,CheckCircle2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import type {Company} from '@/lib/workspace-model';
import type {Service} from '@/lib/company-settings';
function money(value:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value)}
export function ServiceCatalog({company,disabled,onSave}:{company:Company;disabled:boolean;onSave:(payload:unknown)=>Promise<unknown>}){
 const [services,setServices]=useState<Service[]>(company.settings.services),[error,setError]=useState('');
 const patch=(id:string,next:Partial<Service>)=>setServices(list=>list.map(service=>service.id===id?{...service,...next}:service));
 function add(){if(services.length>=50){setError('Você pode cadastrar até 50 serviços.');return;}setServices(list=>[...list,{id:crypto.randomUUID(),name:'',description:'',duration:30,price:0,pricingModel:'fixed',active:true}]);setError('');}
 async function save(){if(!services.length){setError('Cadastre pelo menos um serviço.');return;}if(services.some(service=>!service.name.trim())){setError('Preencha o nome de todos os serviços.');return;}if(new Set(services.map(service=>service.name.trim().toLocaleLowerCase('pt-BR'))).size!==services.length){setError('Não é possível cadastrar serviços com o mesmo nome.');return;}setError('');await onSave({name:company.name,mode:company.mode,version:company.version,settings:{...company.settings,services:services.map(service=>({...service,name:service.name.trim(),description:service.description.trim()}))}});}
 const active=services.filter(service=>service.active),monthly=active.filter(service=>service.pricingModel==='monthly');
 return <section className="panel services-panel"><div className="section-title services-title"><div><p className="eyebrow">CATÁLOGO · {company.settings.sector.toUpperCase()}</p><h2>Serviços e planos</h2><p className="muted">Cadastre o que sua empresa oferece. Os serviços ativos ficam disponíveis na agenda e nos pedidos.</p></div><Button onClick={add} variant="outline"><Plus/>Novo serviço</Button></div>
  <div className="service-metrics"><article><BadgeDollarSign/><div><strong>{services.length}</strong><small>serviços cadastrados</small></div></article><article><CheckCircle2/><div><strong>{active.length}</strong><small>disponíveis para clientes</small></div></article><article><Clock/><div><strong>{monthly.length}</strong><small>planos mensais</small></div></article></div>
  {services.length===0?<div className="services-empty"><BadgeDollarSign/><h3>Cadastre seu primeiro serviço</h3><p>Informe duração, valor e se a cobrança é avulsa, mensal ou definida por orçamento.</p><Button onClick={add}><Plus/>Adicionar serviço</Button></div>:<div className="service-catalog">{services.map((service,index)=><article className={'service-editor '+(!service.active?'inactive':'')} key={service.id}><div className="service-editor-head"><span className="service-number">{String(index+1).padStart(2,'0')}</span><div><strong>{service.name||'Novo serviço'}</strong><small>{service.pricingModel==='monthly'?'Plano mensal':service.pricingModel==='quote'?'Valor sob orçamento':money(service.price)}</small></div><label className="service-active"><input type="checkbox" checked={service.active} onChange={e=>patch(service.id,{active:e.target.checked})}/>Ativo</label><Button type="button" variant="ghost" aria-label={'Remover '+(service.name||'serviço')} onClick={()=>setServices(list=>list.filter(item=>item.id!==service.id))}><Trash2/></Button></div><div className="service-editor-grid"><label>Nome do serviço<Input value={service.name} required maxLength={120} placeholder="Ex.: Corte, consulta ou instalação" onChange={e=>patch(service.id,{name:e.target.value})}/></label><label>Forma de cobrança<NativeSelect value={service.pricingModel} onChange={e=>patch(service.id,{pricingModel:e.target.value as Service['pricingModel']})}><option value="fixed">Valor avulso</option><option value="monthly">Plano mensal</option><option value="quote">Sob orçamento</option></NativeSelect></label><label>Duração média<Input type="number" min={5} max={480} step={5} value={service.duration} onChange={e=>patch(service.id,{duration:Number(e.target.value)})}/><small>Em minutos</small></label><label>Valor {service.pricingModel==='monthly'?'mensal':'do serviço'}<span className="money-input"><b>R$</b><Input type="number" min={0} max={9999999.99} step="0.01" value={service.price} disabled={service.pricingModel==='quote'} onChange={e=>patch(service.id,{price:Number(e.target.value)})}/></span>{service.pricingModel==='quote'&&<small>O valor será definido em cada orçamento.</small>}</label><label className="service-description">Descrição <small>Opcional</small><textarea value={service.description} maxLength={500} placeholder="O que está incluído neste serviço ou plano?" onChange={e=>patch(service.id,{description:e.target.value})}/></label></div></article>)}</div>}
  {error&&<p role="alert" className="notice error-notice">{error}</p>}<div className="services-save"><p className="muted">Valores em reais. Serviços inativos continuam no histórico, mas não aparecem em novos agendamentos.</p><Button onClick={save} disabled={disabled||services.length===0}>{disabled?'Salvando…':'Salvar catálogo'}</Button></div>
 </section>
}
