'use client';
import {useState} from 'react';
import {Plus,Trash2,UsersRound,UserCheck,UserX,Link2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import type {Company} from '@/lib/workspace-model';
import type {TeamMember} from '@/lib/company-settings';
export function TeamManagement({company,disabled,onSave,onAccess}:{company:Company;disabled:boolean;onSave:(payload:unknown)=>Promise<unknown>;onAccess:(professionalId:string)=>Promise<void>}){
 const [hasTeam,setHasTeam]=useState(company.settings.hasTeam),[team,setTeam]=useState<TeamMember[]>(company.settings.team),[error,setError]=useState('');
 const patch=(id:string,next:Partial<TeamMember>)=>setTeam(list=>list.map(member=>member.id===id?{...member,...next}:member));
 function add(){if(team.length>=100){setError('Você pode cadastrar até 100 barbeiros.');return;}setHasTeam(true);setTeam(list=>[...list,{id:crypto.randomUUID(),name:'',role:'Barbeiro',phone:'',email:'',active:true}]);setError('');}
 async function save(){if(team.some(member=>!member.name.trim()||!member.role.trim())){setError('Preencha o nome e a especialidade de cada barbeiro.');return;}setError('');await onSave({name:company.name,mode:company.mode,version:company.version,settings:{...company.settings,hasTeam,team:team.map(member=>({...member,name:member.name.trim(),role:member.role.trim(),phone:member.phone.trim(),email:member.email.trim()}))}});}
 const active=team.filter(member=>member.active).length;
 return <section className="panel team-panel"><div className="section-title"><div><p className="eyebrow">EQUIPE DA BARBEARIA</p><h2>Barbeiros</h2><p className="muted">Cadastre os barbeiros que realizam os atendimentos.</p></div><Button variant="outline" onClick={add}><Plus/>Adicionar barbeiro</Button></div><div className="team-metrics"><article><UsersRound/><div><strong>{team.length}</strong><small>barbeiros cadastrados</small></div></article><article><UserCheck/><div><strong>{active}</strong><small>barbeiros ativos</small></div></article><label className="team-toggle"><input type="checkbox" checked={hasTeam} onChange={event=>setHasTeam(event.target.checked)}/><span><strong>Minha barbearia possui equipe</strong><small>Desative se você trabalha sozinho. Os cadastros serão preservados.</small></span></label></div>
 {team.length===0?<div className="team-empty"><UsersRound/><h3>{hasTeam?'Cadastre a primeira pessoa da equipe':'Você informou que trabalha sozinho'}</h3><p>Quando contratar alguém ou trabalhar com outros profissionais, adicione cada pessoa com sua função ou especialidade.</p><Button onClick={add}><Plus/>Adicionar barbeiro</Button></div>:<div className="team-list">{team.map((member,index)=><article className={'team-editor '+(!member.active?'inactive':'')} key={member.id}><header><span className="team-avatar">{member.name.trim().slice(0,2).toUpperCase()||String(index+1).padStart(2,'0')}</span><div><strong>{member.name||'Novo barbeiro'}</strong><small>{member.role||'Especialidade ainda não informada'}</small></div><label className="service-active"><input type="checkbox" checked={member.active} onChange={event=>patch(member.id,{active:event.target.checked})}/>Ativo</label><Button variant="outline" disabled={disabled||!member.active||!member.name.trim()} onClick={()=>void onAccess(member.id)}><Link2/>Acesso</Button><Button variant="ghost" aria-label={'Remover '+(member.name||'barbeiro')} onClick={()=>setTeam(list=>list.filter(item=>item.id!==member.id))}><Trash2/></Button></header><div className="team-editor-grid"><label>Nome completo<Input value={member.name} required maxLength={100} placeholder="Nome do barbeiro" onChange={event=>patch(member.id,{name:event.target.value})}/></label><label>Especialidade<Input value={member.role} required maxLength={100} placeholder="Ex.: Barbeiro, especialista em barba" onChange={event=>patch(member.id,{role:event.target.value})}/></label><label>Telefone <small>Opcional</small><Input type="tel" value={member.phone} maxLength={20} placeholder="(11) 99999-9999" onChange={event=>patch(member.id,{phone:event.target.value})}/></label><label>E-mail <small>Opcional</small><Input type="email" value={member.email} maxLength={254} placeholder="barbeiro@barbearia.com" onChange={event=>patch(member.id,{email:event.target.value})}/></label></div></article>)}</div>}
 {error&&<p role="alert" className="notice error-notice">{error}</p>}<div className="team-save"><p className="muted"><UserX/> Barbeiros inativos ficam fora de novos atendimentos, mas continuam no histórico.</p><Button onClick={save} disabled={disabled}>{disabled?'Salvando…':'Salvar barbeiros'}</Button></div></section>;
}


