'use client';
import {useState} from 'react';
import {Plus,Trash2,UsersRound,UserCheck,UserX,Link2,CalendarOff,Clock3} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {weekdays,type TeamMember,type AvailabilityBlock} from '@/lib/company-settings';
import type {Company} from '@/lib/workspace-model';

export function TeamManagement({company,disabled,onSave,onAccess}:{company:Company;disabled:boolean;onSave:(payload:unknown)=>Promise<unknown>;onAccess:(professionalId:string)=>Promise<void>}){
 const [hasTeam,setHasTeam]=useState(company.settings.hasTeam),[team,setTeam]=useState<TeamMember[]>(company.settings.team),[error,setError]=useState('');
 const patch=(id:string,next:Partial<TeamMember>)=>setTeam(list=>list.map(member=>member.id===id?{...member,...next}:member));
 const hoursFor=(member:TeamMember)=>member.hours??company.settings.hours;
 const patchHour=(id:string,index:number,next:Partial<ReturnType<typeof hoursFor>[number]>)=>setTeam(list=>list.map(member=>member.id===id?{...member,hours:hoursFor(member).map((hour,i)=>i===index?{...hour,...next}:hour)}:member));
 const patchBlock=(id:string,blockId:string,next:Partial<AvailabilityBlock>)=>setTeam(list=>list.map(member=>member.id===id?{...member,blocks:(member.blocks??[]).map(block=>block.id===blockId?{...block,...next}:block)}:member));
 function add(){if(team.length>=100){setError('Você pode cadastrar até 100 barbeiros.');return;}setHasTeam(true);setTeam(list=>[...list,{id:crypto.randomUUID(),name:'',role:'Barbeiro',phone:'',email:'',active:true,hours:company.settings.hours.map(hour=>({...hour})),blocks:[]}]);setError('');}
 function addBlock(id:string){const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);setTeam(list=>list.map(member=>member.id===id?{...member,blocks:[...(member.blocks??[]),{id:crypto.randomUUID(),date:tomorrow,start:'12:00',end:'13:00',reason:'Indisponível'}]}:member));}
 async function save(){if(team.some(member=>!member.name.trim()||!member.role.trim())){setError('Preencha o nome e a especialidade de cada barbeiro.');return;}setError('');await onSave({name:company.name,mode:company.mode,version:company.version,settings:{...company.settings,hasTeam,team:team.map(member=>({...member,name:member.name.trim(),role:member.role.trim(),phone:member.phone.trim(),email:member.email.trim(),hours:hoursFor(member),blocks:member.blocks??[]}))}});}
 const active=team.filter(member=>member.active).length;
 return <section className="panel team-panel"><div className="section-title"><div><p className="eyebrow">EQUIPE DA BARBEARIA</p><h2>Barbeiros</h2><p className="muted">Cadastre os barbeiros e configure a disponibilidade individual de cada agenda.</p></div><Button variant="outline" onClick={add}><Plus/>Adicionar barbeiro</Button></div>
 <div className="team-metrics"><article><UsersRound/><div><strong>{team.length}</strong><small>barbeiros cadastrados</small></div></article><article><UserCheck/><div><strong>{active}</strong><small>barbeiros ativos</small></div></article><label className="team-toggle"><input type="checkbox" checked={hasTeam} onChange={event=>setHasTeam(event.target.checked)}/><span><strong>Minha barbearia possui equipe</strong><small>Desative se você trabalha sozinho.</small></span></label></div>
 {team.length===0?<div className="team-empty"><UsersRound/><h3>{hasTeam?'Cadastre o primeiro barbeiro':'Você informou que trabalha sozinho'}</h3><p>Adicione cada barbeiro para organizar horários e acessos individuais.</p><Button onClick={add}><Plus/>Adicionar barbeiro</Button></div>:<div className="team-list">{team.map((member,index)=><article className={'team-editor '+(!member.active?'inactive':'')} key={member.id}><header><span className="team-avatar">{member.name.trim().slice(0,2).toUpperCase()||String(index+1).padStart(2,'0')}</span><div><strong>{member.name||'Novo barbeiro'}</strong><small>{member.role||'Especialidade ainda não informada'}</small></div><label className="service-active"><input type="checkbox" checked={member.active} onChange={event=>patch(member.id,{active:event.target.checked})}/>Ativo</label><Button variant="outline" disabled={disabled||!member.active||!member.name.trim()} onClick={()=>void onAccess(member.id)}><Link2/>Acesso</Button><Button variant="ghost" aria-label={'Remover '+(member.name||'barbeiro')} onClick={()=>setTeam(list=>list.filter(item=>item.id!==member.id))}><Trash2/></Button></header>
 <div className="team-editor-grid"><label>Nome completo<Input value={member.name} required maxLength={100} placeholder="Nome do barbeiro" onChange={event=>patch(member.id,{name:event.target.value})}/></label><label>Especialidade<Input value={member.role} required maxLength={100} placeholder="Ex.: Barbeiro, especialista em barba" onChange={event=>patch(member.id,{role:event.target.value})}/></label><label>Telefone <small>Opcional</small><Input type="tel" value={member.phone} maxLength={20} placeholder="(11) 99999-9999" onChange={event=>patch(member.id,{phone:event.target.value})}/></label><label>E-mail <small>Opcional</small><Input type="email" value={member.email} maxLength={254} placeholder="barbeiro@barbearia.com" onChange={event=>patch(member.id,{email:event.target.value})}/></label></div>
 <details className="barber-availability"><summary><Clock3/>Horários, almoço, folgas e ausências</summary><p className="muted">Defina o expediente semanal deste barbeiro. O intervalo bloqueia automaticamente o almoço.</p><div className="barber-hours">{hoursFor(member).map((hour,day)=><div key={day}><label><input type="checkbox" checked={hour.enabled} onChange={event=>patchHour(member.id,day,{enabled:event.target.checked})}/>{weekdays[day]}</label>{hour.enabled?<><Input aria-label={'Entrada '+weekdays[day]} type="time" value={hour.open} onChange={event=>patchHour(member.id,day,{open:event.target.value})}/><Input aria-label={'Saída '+weekdays[day]} type="time" value={hour.close} onChange={event=>patchHour(member.id,day,{close:event.target.value})}/><Input aria-label={'Início do almoço '+weekdays[day]} type="time" value={hour.breakStart} onChange={event=>patchHour(member.id,day,{breakStart:event.target.value})}/><Input aria-label={'Fim do almoço '+weekdays[day]} type="time" value={hour.breakEnd} onChange={event=>patchHour(member.id,day,{breakEnd:event.target.value})}/></>:<span className="muted">Folga</span>}</div>)}</div>
 <div className="blocks-title"><div><h3>Bloqueios por data</h3><small>Use para folga, consulta, férias ou outra ausência.</small></div><Button variant="outline" onClick={()=>addBlock(member.id)}><CalendarOff/>Adicionar bloqueio</Button></div>
 {(member.blocks??[]).map(block=><div className="barber-block" key={block.id}><Input type="date" value={block.date} onChange={event=>patchBlock(member.id,block.id,{date:event.target.value})}/><Input aria-label="Início do bloqueio" type="time" value={block.start} onChange={event=>patchBlock(member.id,block.id,{start:event.target.value})}/><Input aria-label="Fim do bloqueio" type="time" value={block.end} onChange={event=>patchBlock(member.id,block.id,{end:event.target.value})}/><Input value={block.reason} maxLength={100} placeholder="Motivo" onChange={event=>patchBlock(member.id,block.id,{reason:event.target.value})}/><Button variant="ghost" aria-label="Remover bloqueio" onClick={()=>patch(member.id,{blocks:(member.blocks??[]).filter(item=>item.id!==block.id)})}><Trash2/></Button></div>)}</details>
 </article>)}</div>}
 {error&&<p role="alert" className="notice error-notice">{error}</p>}<div className="team-save"><p className="muted"><UserX/> Barbeiros inativos ficam fora de novos atendimentos, mas continuam no histórico.</p><Button onClick={save} disabled={disabled}>{disabled?'Salvando…':'Salvar barbeiros e horários'}</Button></div></section>;
}

