export type BusinessProfile={
 customerSingular:string;customers:string;customersBase:string;agenda:string;appointmentSingular:string;appointmentsToday:string;
 team:string;services:string;workSingular:string;workPlural:string;newWork:string;subtitle:string;managerTitle:string;managerEmpty:string;managerBody:(count:number)=>string;
 requestLabel:string;extraLabel:string;extraPlaceholder:string;siteLabel:string;
};
const generic:BusinessProfile={customerSingular:'cliente',customers:'Clientes',customersBase:'Base de clientes',agenda:'Agenda',appointmentSingular:'atendimento',appointmentsToday:'Atendimentos hoje',team:'Equipe',services:'Serviços',workSingular:'solicitação',workPlural:'Solicitações',newWork:'Nova solicitação',subtitle:'Clientes, serviços e atividades em um só lugar.',managerTitle:'Atividades que precisam avançar',managerEmpty:'Comece cadastrando seu primeiro cliente.',managerBody:count=>`Você tem ${count} solicitações em andamento. Acompanhe responsáveis, informações e próximas etapas.`,requestLabel:'Detalhes da solicitação',extraLabel:'Informações adicionais',extraPlaceholder:'Inclua informações importantes para realizar o serviço.',siteLabel:'Local do atendimento'};
const profiles:Record<string,Partial<BusinessProfile>>={
 'vidracaria':{agenda:'Visitas e agenda',appointmentsToday:'Visitas hoje',workSingular:'pedido',workPlural:'Pedidos e orçamentos',newWork:'Novo pedido',subtitle:'Do primeiro orçamento à instalação concluída.',managerTitle:'Pedidos que precisam avançar',managerEmpty:'Comece cadastrando o primeiro cliente.',managerBody:count=>`Você tem ${count} pedidos abertos. Acompanhe medidas, orçamento, produção e instalação.`,requestLabel:'Descrição do pedido',extraLabel:'Medidas informadas',extraPlaceholder:'Ex.: largura 1,20 m × altura 1,90 m. Sujeitas à conferência técnica.',siteLabel:'Endereço da obra'},
 'mecanica':{agenda:'Agenda da oficina',team:'Mecânicos',workSingular:'ordem de serviço',workPlural:'Ordens de serviço',newWork:'Nova ordem de serviço',subtitle:'Clientes, veículos e serviços da oficina organizados.',managerTitle:'Serviços que precisam avançar',managerBody:count=>`Você tem ${count} serviços em andamento. Acompanhe diagnóstico, responsável e execução.`,requestLabel:'Relato e diagnóstico',extraLabel:'Veículo e observações técnicas',extraPlaceholder:'Informe veículo, placa, quilometragem e observações.',siteLabel:'Local do serviço'},
 'personal trainer':{customerSingular:'aluno',customers:'Alunos',customersBase:'Base de alunos',agenda:'Treinos',appointmentSingular:'treino',appointmentsToday:'Treinos hoje',team:'Profissionais',services:'Planos e serviços',subtitle:'Alunos, treinos e planos organizados.'},
 'clinica':{customerSingular:'paciente',customers:'Pacientes',customersBase:'Base de pacientes',agenda:'Consultas',appointmentSingular:'consulta',appointmentsToday:'Consultas hoje',team:'Profissionais',subtitle:'Pacientes, profissionais e consultas organizados.'},
 'barbearia':{agenda:'Agenda',appointmentSingular:'horário',appointmentsToday:'Horários hoje',team:'Barbeiros',services:'Serviços e planos',subtitle:'Clientes, barbeiros e horários organizados.'},
 'salao de beleza':{agenda:'Agenda',appointmentSingular:'horário',appointmentsToday:'Horários hoje',team:'Profissionais',services:'Serviços e pacotes',subtitle:'Clientes, profissionais e horários organizados.'}
};
function normalized(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLocaleLowerCase('pt-BR')}
export function businessProfile(sector:string):BusinessProfile{const key=normalized(sector),match=Object.keys(profiles).find(name=>key.includes(name));return {...generic,...(match?profiles[match]:{})};}
