import {AppError,object,text,address} from './workspace-validation.ts';
import {timezones,moduleNames,minute,businessDay,type CompanySettings,type ModuleId} from './company-settings.ts';
function time(value:unknown){const v=text(value,5,true);if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(v))throw new AppError(400,'Informe horários válidos.');return v;}
export function validateSettings(value:unknown):CompanySettings{
 const p=object(value);const sector=text(p.sector,80,true);if(sector.length<2)throw new AppError(400,'Informe o ramo de atividade da empresa.');
 const phone=text(p.phone,20).replace(/\D/g,'');if(phone&&!/^\d{10,11}$/.test(phone))throw new AppError(400,'Informe telefone com DDD.');
 const email=text(p.email,254).toLowerCase();if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new AppError(400,'Informe um e-mail válido.');
 const timezone=text(p.timezone,60,true);if(!(timezones as readonly string[]).includes(timezone))throw new AppError(400,'Selecione um fuso horário válido.');
 if(!Array.isArray(p.services)||p.services.length>50)throw new AppError(400,'Cadastre até 50 serviços.');
 const ids=new Set(),names=new Set();
 const services=p.services.map(value=>{const s=object(value);const id=text(s.id,80,true),name=text(s.name,120,true);if(!/^[a-zA-Z0-9_-]+$/.test(id)||ids.has(id)||names.has(name.toLocaleLowerCase('pt-BR')))throw new AppError(400,'Não repita serviços ou identificadores.');ids.add(id);names.add(name.toLocaleLowerCase('pt-BR'));if(!Number.isInteger(s.duration)||Number(s.duration)<5||Number(s.duration)>480||typeof s.active!=='boolean')throw new AppError(400,'A duração do serviço deve ser de 5 a 480 minutos.');const pricingModel=s.pricingModel===undefined?'fixed':text(s.pricingModel,20,true);if(!['fixed','monthly','quote'].includes(pricingModel))throw new AppError(400,'Forma de cobrança inválida.');const price=s.price===undefined?0:Number(s.price);if(!Number.isFinite(price)||price<0||price>9999999.99)throw new AppError(400,'Informe um valor válido para o serviço.');return {id,name,description:text(s.description,500),duration:Number(s.duration),price:Math.round(price*100)/100,pricingModel:pricingModel as 'fixed'|'monthly'|'quote',active:s.active};});
 if(!Array.isArray(p.hours)||p.hours.length!==7)throw new AppError(400,'Configure os sete dias da semana.');
 const hours=p.hours.map((value,day)=>{const h=object(value);if(h.day!==day||typeof h.enabled!=='boolean')throw new AppError(400,'Dia da semana inválido.');const open=time(h.open),close=time(h.close);if(minute(open)>=minute(close))throw new AppError(400,'O fechamento deve ser depois da abertura, no mesmo dia.');const breakStart=h.breakStart?time(h.breakStart):'',breakEnd=h.breakEnd?time(h.breakEnd):'';if(!!breakStart!==!!breakEnd||(breakStart&&!(minute(open)<minute(breakStart)&&minute(breakStart)<minute(breakEnd)&&minute(breakEnd)<minute(close))))throw new AppError(400,'O intervalo deve ficar dentro do expediente, com início e fim.');return {day,enabled:h.enabled,open,close,breakStart,breakEnd};});
 if(!Array.isArray(p.modules)||p.modules.length<1)throw new AppError(400,'Selecione ao menos uma ferramenta para a empresa.');const modules=[...new Set(p.modules.map(value=>text(value,30,true)))];if(modules.some(value=>!(value in moduleNames)))throw new AppError(400,'Ferramenta da empresa inválida.');
 if(!Array.isArray(p.team)||p.team.length>100)throw new AppError(400,'Cadastre até 100 profissionais.');const memberIds=new Set();const team=p.team.map(value=>{const member=object(value),id=text(member.id,80,true),name=text(member.name,100,true),role=text(member.role,100,true),phone=text(member.phone,20).replace(/\D/g,''),email=text(member.email,254).toLowerCase();if(!/^[a-zA-Z0-9_-]+$/.test(id)||memberIds.has(id))throw new AppError(400,'Profissional duplicado ou inválido.');memberIds.add(id);if(phone&&!/^\d{10,11}$/.test(phone))throw new AppError(400,'Informe o telefone do profissional com DDD.');if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new AppError(400,'Informe um e-mail válido para o profissional.');if(typeof member.active!=='boolean')throw new AppError(400,'Situação do profissional inválida.');return {id,name,role,phone,email,active:member.active};});
 return {sector,phone,email,address:address(p.address),timezone,services,hours,modules:modules as ModuleId[],hasTeam:p.hasTeam===true,team,onboardingComplete:p.onboardingComplete===true};
}
export function configuredSchedule(p:Record<string,unknown>,settings:CompanySettings){
 const date=text(p.date,10,true),start=time(p.time);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date+'T12:00:00Z'))||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)throw new AppError(400,'Data inválida.');
 const serviceId=text(p.serviceId,80);const service=settings.services.find(s=>s.id===serviceId&&s.active);
 if((serviceId||settings.services.length>0)&&!service)throw new AppError(400,'Selecione um serviço ativo em Empresa e Configurações.');
 const duration=service?service.duration:Number(p.duration);if(!Number.isInteger(duration)||duration<5||duration>480)throw new AppError(400,'Informe duração de 5 a 480 minutos.');
 const day=businessDay(date,settings),startMinute=minute(start),end=startMinute+duration;
 if(!day?.enabled)throw new AppError(400,'A empresa está fechada nesse dia.');
 if(startMinute<minute(day.open)||end>minute(day.close)||(day.breakStart&&startMinute<minute(day.breakEnd)&&end>minute(day.breakStart)))throw new AppError(400,'O atendimento deve caber no expediente e respeitar o intervalo.');
 return {date,time:start,startMinute,duration,kind:service?.name??'Atendimento'};
}
