import {addressError,clientError,hasAddress,type Address,type AttendanceMode} from './customer-rules.ts';
import {orderStatuses} from './workspace-model.ts';
export class AppError extends Error{status:number;constructor(status:number,message:string){super(message);this.status=status;}}
export function mutationOrigin(req:Request){const origin=req.headers.get('origin'),forwardedHost=(req.headers.get('x-forwarded-host')||req.headers.get('host')||'').split(',')[0].trim(),forwardedProto=(req.headers.get('x-forwarded-proto')||'https').split(',')[0].trim(),allowed=new Set<string>([new URL(req.url).origin]);if(forwardedHost)allowed.add(`${forwardedProto}://${forwardedHost}`);const configured=process.env.NEXT_PUBLIC_SITE_URL;try{if(configured)allowed.add(new URL(configured).origin)}catch{}if(req.headers.get('sec-fetch-site')==='cross-site'||!origin||!allowed.has(origin))throw new AppError(403,'Origem da solicitação não autorizada. Atualize a página.');}
export function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new AppError(400,'Dados inválidos.');return value as Record<string,unknown>;}
export function text(value:unknown,max:number,required=false):string{if(value!==undefined&&typeof value!=='string')throw new AppError(400,'Campo de texto inválido.');const result=(value as string|undefined)?.trim()??'';if(result.length>max||(required&&!result))throw new AppError(400,'Preencha os campos obrigatórios e respeite o tamanho máximo.');return result;}
export function version(value:unknown):number{if(!Number.isSafeInteger(value)||Number(value)<1)throw new AppError(400,'Versão inválida. Atualize a página.');return Number(value);}
export function mode(value:unknown):AttendanceMode{if(value!=='customer'&&value!=='business'&&value!=='both')throw new AppError(400,'Tipo de atendimento inválido.');return value;}
export function address(value:unknown,required=false):Address|undefined{if(value===undefined||value===null){if(required)throw new AppError(400,'Informe o endereço completo.');return undefined;}const a=object(value);const result:Address={street:text(a.street,150),number:text(a.number,20),neighborhood:text(a.neighborhood,100),city:text(a.city,100),state:text(a.state,2).toUpperCase(),postalCode:text(a.postalCode,9),complement:text(a.complement,150)};if(!required&&!hasAddress(result))return undefined;const error=addressError(result);if(error)throw new AppError(400,error);return result;}
export function customer(payload:Record<string,unknown>,attendance:AttendanceMode){const name=text(payload.name,100,true);const phone=text(payload.phone,20,true);const a=address(payload.address,attendance==='customer');const error=clientError(name,phone,a,attendance);if(error)throw new AppError(400,error);return {name,phone:phone.replace(/\D/g,''),address:a};}
export function orderStatus(value:unknown){if(!(orderStatuses as readonly unknown[]).includes(value))throw new AppError(400,'Etapa do pedido inválida.');return value as typeof orderStatuses[number];}
export function schedule(payload:Record<string,unknown>){const date=text(payload.date,10,true);const time=text(payload.time,5,true);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date+'T12:00:00Z'))||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)throw new AppError(400,'Data inválida.');if(!/^\d{2}:\d{2}$/.test(time))throw new AppError(400,'Horário inválido.');const [h,m]=time.split(':').map(Number);const duration=Number(payload.duration);if(h>23||m>59||![30,60,90,120].includes(duration)||h*60+m<540||h*60+m+duration>1080)throw new AppError(400,'Escolha duração de 30 a 120 minutos, dentro do expediente de 09:00 às 18:00.');const kind=text(payload.kind,30,true);if(!['Medição','Instalação','Atendimento'].includes(kind))throw new AppError(400,'Tipo de compromisso inválido.');return {date,time,startMinute:h*60+m,duration,kind};}
export function imageMime(bytes:Uint8Array):string|null{if(bytes.length>=3&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return 'image/jpeg';if(bytes.length>=8&&[137,80,78,71,13,10,26,10].every((n,i)=>bytes[i]===n))return 'image/png';if(bytes.length>=12&&String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP')return 'image/webp';return null;}
