import 'server-only';
import {cookies} from 'next/headers';
import {createServerClient} from '@supabase/ssr';
import {createClient} from '@supabase/supabase-js';
import {AppError} from '@/lib/workspace-validation';
export async function sessionClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw new AppError(503,'Configure o Supabase para ativar o acesso ao sistema.');const jar=await cookies();return createServerClient(url,key,{cookies:{getAll:()=>jar.getAll(),setAll:items=>{for(const {name,value,options} of items)jar.set(name,value,options);}}});}
export function adminClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY;if(!url||!key)throw new AppError(503,'A conexão com o banco ainda precisa ser configurada.');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});}
export async function context(_req:Request){const auth=await sessionClient();const {data,error}=await auth.auth.getUser();if(error||!data.user)throw new AppError(401,'Entre com sua conta para acessar os registros.');const tenant=data.user.id,db=adminClient();checked(await db.from('companies').upsert({id:tenant,name:'Minha empresa',mode:'business'},{onConflict:'id',ignoreDuplicates:true}));return {tenant,db};}
export function checked<T>(r:{data:T;error:unknown}):NonNullable<T>{if(r.error)throw r.error;return r.data as NonNullable<T>;}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'private, no-store','Vary':'Cookie','X-Content-Type-Options':'nosniff'}});}
export function failure(error:unknown){if(error instanceof AppError)return json({error:error.message},error.status);const e=error as {code?:string;message?:string};if(e.code==='23P01'||e.message?.includes('booking_overlap'))return json({error:'Esse horário conflita com outro agendamento.'},409);if(e.message?.includes('photo_limit'))return json({error:'O pedido já tem 5 fotos.'},409);if(e.message?.includes('stale_company'))return json({error:'Configurações alteradas. Atualize a agenda.'},409);if(e.code==='23505')return json({error:'Já existe um registro com esses dados. Confira o telefone do cliente.'},409);if(e.code==='23503')return json({error:'O registro relacionado não está disponível.'},409);console.error('Operation failed',e.code??'unknown');return json({error:'Não foi possível concluir. Confira a configuração do Supabase ou tente novamente.'},500);}
export async function readJson(req:Request){if(!req.headers.get('content-type')?.includes('application/json'))throw new AppError(415,'Envie dados JSON.');const body=await req.text();if(body.length>24000)throw new AppError(413,'Dados muito grandes.');try{return JSON.parse(body)}catch{throw new AppError(400,'Dados inválidos.');}}
export function changed(rows:unknown[]|null){if(!rows?.length)throw new AppError(409,'O registro foi alterado ou não está disponível. Atualize os dados.');}
export function fileResponse(blob:Blob){return new Response(blob,{headers:{'Content-Type':blob.type||'application/octet-stream','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"}});}
export const storageBucket='orbita-files';
