-- Run once in a NEW Supabase project. No existing records are deleted.
begin;
create schema if not exists extensions;
create extension if not exists btree_gist with schema extensions;
set local search_path = public, extensions;
create table public.companies (
 id uuid primary key, name text not null check(length(name) between 1 and 100),
 mode text not null check(mode in ('business','customer','both')),
 version integer not null default 1 check(version>0),settings jsonb,logo_key text);
create table public.customers (
 id text primary key,tenant uuid not null references public.companies(id),
 name text not null,phone text not null,address jsonb,notes text not null default '',preferred_professional_id text,version integer not null default 1,
 created_at timestamptz not null default now(),unique(tenant,id),unique(tenant,phone));
create table public.orders (
 id text primary key,tenant uuid not null references public.companies(id),customer_id text not null,
 service text not null,description text not null,measurements text not null default '',responsible text not null default '',
 address jsonb,status text not null,version integer not null default 1,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 unique(tenant,id),foreign key(tenant,customer_id) references public.customers(tenant,id));
create index orders_tenant_created on public.orders(tenant,created_at);
create table public.bookings (
 id text primary key,tenant uuid not null references public.companies(id),customer_id text not null,
 date date not null,time text not null check(time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
 start_minute integer not null check(start_minute between 0 and 1439),
 duration integer not null check(duration between 5 and 480),
 kind text not null,professional_id text,public_token_hash text,location text not null check(location in ('customer','business')),address jsonb,
 status text not null check(status in ('Pendente','Confirmado','Concluído','Cancelado')),version integer not null default 1,
 check(start_minute+duration<=1440),
 foreign key(tenant,customer_id) references public.customers(tenant,id),
 constraint booking_overlap exclude using gist(tenant with =,date with =,(coalesce(professional_id,'__solo__')) with =,int4range(start_minute,start_minute+duration,'[)') with &&) where (status<>'Cancelado'));
create index bookings_tenant_date on public.bookings(tenant,date);
create table public.photos (
 id text primary key,tenant uuid not null,order_id text not null,object_key text not null unique,
 name text not null,mime text not null,size integer not null check(size>0 and size<=4194304),
 created_at timestamptz not null default now(),
 foreign key(tenant,order_id) references public.orders(tenant,id));
create index photos_tenant_order on public.photos(tenant,order_id);
create table public.audit (
 id bigint generated by default as identity primary key,tenant uuid not null,entity text not null,entity_id text not null,
 action text not null,created_at timestamptz not null default now());
create index audit_tenant_id on public.audit(tenant,id);
-- Browser roles cannot bypass application validation. Only the verified server can write.
alter table public.companies enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.bookings enable row level security;
alter table public.photos enable row level security;
alter table public.audit enable row level security;
revoke all on public.companies,public.customers,public.orders,public.bookings,public.photos,public.audit from anon,authenticated;
grant all on public.companies,public.customers,public.orders,public.bookings,public.photos,public.audit to service_role;
grant usage,select on sequence public.audit_id_seq to service_role;

create function public.record_change() returns trigger language plpgsql set search_path='' as $$
begin
 insert into public.audit(tenant,entity,entity_id,action)
 values(NEW.tenant,TG_TABLE_NAME,NEW.id::text,
 case when TG_OP='INSERT' then 'Criado' else 'Atualizado' end);
 return NEW;
end $$;
-- Separate company trigger because that row has no tenant column.
create function public.record_company_change() returns trigger language plpgsql set search_path='' as $$
begin
 insert into public.audit(tenant,entity,entity_id,action) values(NEW.id,'companies',NEW.id::text,'Atualizado');
 return NEW;
end $$;
create trigger company_audit after update on public.companies for each row execute function public.record_company_change();
create trigger customers_audit after insert or update on public.customers for each row execute function public.record_change();
create trigger orders_audit after insert or update on public.orders for each row execute function public.record_change();
create trigger bookings_audit after insert or update on public.bookings for each row execute function public.record_change();
create trigger photos_audit after insert on public.photos for each row execute function public.record_change();
create function public.limit_photos() returns trigger language plpgsql set search_path='' as $$
begin
 perform 1 from public.orders where id=NEW.order_id and tenant=NEW.tenant for update;
 if (select count(*) from public.photos where order_id=NEW.order_id and tenant=NEW.tenant)>=5 then raise exception 'photo_limit';end if;
 return NEW;
end $$;
create trigger photo_limit before insert on public.photos for each row execute function public.limit_photos();
create function public.create_booking(p_tenant uuid,p_version integer,p_booking jsonb) returns void
 language plpgsql set search_path='' as $$
declare current_version integer;
begin
 select version into current_version from public.companies where id=p_tenant for update;
 if current_version is null or current_version<>p_version then raise exception 'stale_company';end if;
 insert into public.bookings(id,tenant,customer_id,date,time,start_minute,duration,kind,professional_id,public_token_hash,location,address,status)
 values(p_booking->>'id',p_tenant,p_booking->>'customer_id',(p_booking->>'date')::date,p_booking->>'time',
 (p_booking->>'start_minute')::integer,(p_booking->>'duration')::integer,p_booking->>'kind',nullif(p_booking->>'professional_id',''),nullif(p_booking->>'public_token_hash',''),p_booking->>'location',nullif(p_booking->'address','null'::jsonb),'Pendente');
end $$;
revoke all on function public.create_booking(uuid,integer,jsonb),public.record_change(),public.record_company_change(),public.limit_photos() from public,anon,authenticated;
grant execute on function public.create_booking(uuid,integer,jsonb),public.record_change(),public.record_company_change(),public.limit_photos() to service_role;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
 values('orbita-files','orbita-files',false,4194304,array['image/png','image/jpeg','image/webp']);
-- No browser storage policies: files are served by authenticated, tenant-scoped application routes.
commit;



