begin;

create table if not exists public.public_booking_attempts (
 id bigint generated by default as identity primary key,
 tenant uuid not null references public.companies(id) on delete cascade,
 fingerprint text not null,
 phone_hash text,
 created_at timestamptz not null default now()
);
create index if not exists public_booking_attempts_fingerprint on public.public_booking_attempts(tenant,fingerprint,created_at desc);
create index if not exists public_booking_attempts_phone on public.public_booking_attempts(tenant,phone_hash,created_at desc) where phone_hash is not null;
alter table public.public_booking_attempts enable row level security;
revoke all on public.public_booking_attempts from anon,authenticated;
grant all on public.public_booking_attempts to service_role;

create or replace function public.delete_company_data(p_tenant uuid) returns void
language plpgsql security definer set search_path='' as $$
begin
 delete from public.public_booking_attempts where tenant=p_tenant;
 delete from public.client_plans where tenant=p_tenant;
 delete from public.barber_access where tenant=p_tenant;
 delete from public.photos where tenant=p_tenant;
 delete from public.orders where tenant=p_tenant;
 delete from public.bookings where tenant=p_tenant;
 delete from public.customers where tenant=p_tenant;
 delete from public.audit where tenant=p_tenant;
 delete from public.companies where id=p_tenant;
end $$;
revoke all on function public.delete_company_data(uuid) from public,anon,authenticated;
grant execute on function public.delete_company_data(uuid) to service_role;

commit;
